#include "Misc/Constants.h"

#include "Annealing.h"
#include "StopCriteria.h"
#include "Movers.h"
#include "Cooler.h"
#include "Solution.h"
#include "Criteria.h"
#include "Constraints.h"

#include "Annealing.cpp"
#include "StopCriteria.cpp"
#include "Movers.cpp"
#include "Cooler.cpp"
#include "Solution.cpp"
#include "Criteria.cpp"
#include "Constraints.cpp"
